name: build-windows-installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build binaries (PyInstaller)
        shell: cmd
        run: packaging\windows\build.bat

      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup -y

      - name: Compile installer (Inno Setup)
        shell: powershell
        run: |
          $iscc = "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe"
          & "$iscc" "/Odist-installer" "packaging\\windows\\installer.iss"

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist-installer\SERP-Companion-Setup.exe
          if-no-files-found: error

